### ISSUE TITLE
Accessing injected java map values as JS Object properties

### ISSUE THREAD

**Issue by newk5** [alicorn-systems/v8-adapter#19]
Apologies for opening this issue as I've noticed this has been talked before (#11) but I'm a little confused. Is this possible to do somehow with a V8JavaClassInterceptor right now? Or is this a planned feature for the new restructure? If this is possible to achieve with the current version, could you provide an example of how to do it?

**Comment by AlexTrotsenko** [comment]
@newk5  I have tried to use interceptor api, but was not able to achieve the goal without passing original java object in interceptor call-back. 
The change is in the PR https://github.com/alicorn-systems/v8-adapter/pull/28.

Until it's review and merged by @crahda you can get using jitpack:

**Comment by crahda** [comment]
These changes are now available in `1.59-SNAPSHOT`, and will be available in `1.59` sometime in the next few days!
