### ISSUE TITLE
Add ability to read data from V8 JS object

### ISSUE THREAD

**Issue by AlexTrotsenko** [alicorn-systems/v8-adapter#7]
Right now when class is "injected" to V8, it's methods could have arguments as
-  primitives & String 
- or another Java class, which was injected from Java to V8 previously.

For example, there is no way to read data from JS object `{y: 'done'}` when it passed to java method -  following exception is thrown:

```
IllegalArgumentException: No signature exists for readJsObjectAsJavaObjectAndTryGetY with parameters [[object Object], ].
``` 

Instead, when there is call similar to `x.readJsObjectAsMapAndGetY({y: 'done'})`, it should try to _"translate"_ the content of the _JS object_ to Java object, e.g. _Map_. 
Here **x** is our Java class.

**Comment by AlexTrotsenko** [comment]
Pull request is ready: https://github.com/alicorn-systems/v8-adapter/pull/8

**Comment by crahda** [comment]
Awesome, will review your PR and leave any comments on this feature there. Please do look into arrays; I remember them being a complicated problem that I couldn't justify work for at the time...would be interested to see what you find.

I've responded to #5 just now; it looks like it can be solved using our dynamic interface generation feature, so I am going to close it for now.

**Comment by crahda** [comment]
Excellent! I will review #9 ; there's a lot of code there. 

Refer to this test:

https://github.com/alicorn-systems/v8-adapter/blob/master/src/test/java/io/alicorn/v8/V8JavaAdapterTest.java#L288

For an example of dynamic function injection.

**Comment by AlexTrotsenko** [comment]
@crahda I have checked this Junit test and related functionality and it's great. 
_(Looks like since I have not used yet this JS call-backs - I have missed it.)_

**Comment by crahda** [comment]
Awesome, glad to hear it!
